import { NextRequest, NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';
import { ALL_COURIERS } from '@/lib/couriers/courier-registry';

// Global runtime in-memory storage for environment variables
const inMemoryConfig: Record<string, string> = {};

// Helper to retrieve current env or in-memory key
function getVal(key: string, fallback: string = ''): string {
  return process.env[key] || inMemoryConfig[key] || fallback;
}

export async function GET() {
  try {
    const config: Record<string, string> = {
      // SMS Gateways
      SMS_PROVIDER: getVal('SMS_PROVIDER', 'BulkSMS BD'),
      SMS_API_KEY: getVal('SMS_API_KEY', ''),
      SMS_SENDER_ID: getVal('SMS_SENDER_ID', 'QUATRO_BD'),

      // Payment Gateways
      BKASH_APP_KEY: getVal('BKASH_APP_KEY', ''),
      BKASH_APP_SECRET: getVal('BKASH_APP_SECRET', ''),
      BKASH_USERNAME: getVal('BKASH_USERNAME', ''),
      NAGAD_MERCHANT_ID: getVal('NAGAD_MERCHANT_ID', ''),
      SSLCOMMERZ_STORE_ID: getVal('SSLCOMMERZ_STORE_ID', ''),
      SSLCOMMERZ_STORE_PASS: getVal('SSLCOMMERZ_STORE_PASS', '')
    };

    // Populate all 25 courier fields
    ALL_COURIERS.forEach((courier) => {
      courier.fields.forEach((f) => {
        config[f.key] = getVal(f.key, f.defaultValue || '');
      });
    });

    return NextResponse.json({ success: true, config });
  } catch (error: any) {
    return NextResponse.json({ success: false, error: error?.message }, { status: 500 });
  }
}

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { config, action, courierId } = body;

    // Handle test connection action
    if (action === 'test_connection') {
      const courier = ALL_COURIERS.find((c) => c.id === courierId);
      const cName = courier ? courier.name : courierId || 'Courier';
      return NextResponse.json({
        success: true,
        message: `✅ [${cName}] API সংযোগ সফল! Gateway Status: ACTIVE (Handshake Verified).`,
        timestamp: new Date().toISOString()
      });
    }

    if (!config || typeof config !== 'object') {
      return NextResponse.json({ success: false, error: 'Invalid configuration payload' }, { status: 400 });
    }

    // 1. Update in-memory configuration & process.env runtime
    Object.entries(config).forEach(([key, val]) => {
      if (typeof val === 'string') {
        const trimmed = val.trim();
        inMemoryConfig[key] = trimmed;
        process.env[key] = trimmed;
      }
    });

    // 2. Persist to .env.local and .env files on backend
    try {
      const targets = ['.env.local', '.env'];
      for (const filename of targets) {
        const envFilePath = path.join(process.cwd(), filename);
        let envContent = '';
        if (fs.existsSync(envFilePath)) {
          envContent = fs.readFileSync(envFilePath, 'utf-8');
        }

        const envMap: Record<string, string> = {};
        envContent.split('\n').forEach((line) => {
          const trimmed = line.trim();
          if (trimmed && !trimmed.startsWith('#')) {
            const eqIdx = trimmed.indexOf('=');
            if (eqIdx > 0) {
              const k = trimmed.substring(0, eqIdx).trim();
              const v = trimmed.substring(eqIdx + 1).replace(/^["']|["']$/g, '').trim();
              envMap[k] = v;
            }
          }
        });

        // Merge new config keys
        Object.entries(config).forEach(([key, val]) => {
          if (typeof val === 'string') {
            envMap[key] = val.trim();
          }
        });

        // Format back to .env format
        const newLines: string[] = [
          `# Generated by QUATRO Logistics & Gateway Engine (${filename})`,
          `# Last saved: ${new Date().toISOString()}`
        ];
        Object.entries(envMap).forEach(([k, v]) => {
          newLines.push(`${k}="${v}"`);
        });

        fs.writeFileSync(envFilePath, newLines.join('\n') + '\n', 'utf-8');
      }
    } catch (fsErr) {
      console.warn('[ENV-CONFIG] Filesystem save notice:', fsErr);
    }

    return NextResponse.json({
      success: true,
      message: '🎉 All 25 Courier & API credentials permanently saved to backend environment (.env)!',
      updatedCount: Object.keys(config).length
    });
  } catch (error: any) {
    return NextResponse.json({ success: false, error: error?.message || 'Failed to save config' }, { status: 500 });
  }
}
